### ISSUE TITLE
unmute request for KRNL MAIN DISCORD

### ISSUE THREAD

**Issue by chadJR3000** [Krnl-staff/documentation#6]
so i got muted for reporting the 268 kick to 1 of the krnl admins and im requesting unmute because i can only download krnl through the k!tags in the bot cmds server and i cant download through site my discord username is 𝕋𝕣𝕩𝕡z̶シ✞#5192 im hoping to get unmuted

**Comment by GabssXR** [comment]
same i got muted

**Comment by br0k3xn** [comment]
Same, I got muted.
